version: '3'
services:
  static_site:
    image: nginx:alpine
    container_name: adamenkulcomtr
    ports:
      - "172.16.16.23:8080:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    logging:
      driver: gelf
      options:
        gelf-address: "udp://192.168.216.113:12201"
        tag: "adamenkul.org"
